export const projects = [
    {
        id: "1",
        title: "Website Redesign",
        createdAt: "03.06.2024",
        members: 5,
        isOwner: true,
        status: "active",
        tasks: {
            total: 12,
            completed: 8,
        },
    },
    {
        id: "2",
        title: "Mobile App Development",
        createdAt: "11.05.2024",
        members: 8,
        isOwner: false,
        status: "paused",
        tasks: {
            total: 24,
            completed: 20,
        },
    },
    {
        id: "3",
        title: "Marketing Campaign",
        createdAt: "10.03.2024",
        members: 3,
        isOwner: true,
        status: "completed",
        tasks: {
            total: 15,
            completed: 15,
        },
    },
    {
        id: "4",
        title: "Data Analytics Dashboard",
        createdAt: "10.06.2024",
        members: 6,
        isOwner: true,
        status: "active",
        tasks: {
            total: 18,
            completed: 7,
        },
    },
    {
        id: "5",
        title: "User Authentication System",
        createdAt: "05.04.2024",
        members: 4,
        isOwner: false,
        status: "paused",
        tasks: {
            total: 16,
            completed: 4,
        },
    },
    {
        id: "6",
        title: "Cloud Migration",
        createdAt: "12.05.2024",
        members: 7,
        isOwner: true,
        status: "active",
        tasks: {
            total: 22,
            completed: 15,
        },
    },
    {
        id: "7",
        title: "Mobile App Testing",
        createdAt: "15.04.2024",
        members: 5,
        isOwner: false,
        status: "completed",
        tasks: {
            total: 14,
            completed: 14,
        },
    },
    {
        id: "8",
        title: "API Integration",
        createdAt: "20.04.2025",
        members: 4,
        isOwner: true,
        status: "active",
        tasks: {
            total: 20,
            completed: 12,
        },
    },
    {
        id: "9",
        title: "Performance Optimization",
        createdAt: "25.04.2024",
        members: 3,
        isOwner: true,
        status: "paused",
        tasks: {
            total: 10,
            completed: 3,
        },
    },
    {
        id: "10",
        title: "AI Integration Project",
        createdAt: "15.01.2024",
        members: 8,
        isOwner: true,
        status: "active",
        tasks: {
            total: 25,
            completed: 0,
        },
    },
    {
        id: "11",
        title: "Blockchain Implementation",
        createdAt: "01.03.2024",
        members: 6,
        isOwner: false,
        status: "paused",
        tasks: {
            total: 18,
            completed: 2,
        },
    },
    {
        id: "12",
        title: "IoT Platform Development",
        createdAt: "20.04.2023",
        members: 10,
        isOwner: true,
        status: "active",
        tasks: { total: 32, completed: 22 }
    },
    {
        id: "22",
        title: "Social Media Integration",
        createdAt: "01.07.2023",
        members: 4,
        isOwner: false,
        status: "paused",
        tasks: { total: 16, completed: 4 }
    },
    {
        id: "13",
        title: "5G Network Integration",
        createdAt: "10.06.2023",
        members: 12,
        isOwner: true,
        status: "active",
        tasks: {
            total: 40,
            completed: 0,
        },
    },
    {
        id: "14",
        title: "Quantum Computing Research",
        createdAt: "01.05.2023",
        members: 7,
        isOwner: false,
        status: "paused",
        tasks: {
            total: 15,
            completed: 3,
        },
    }
] 