export const projects = [
    {
        id: "1",
        name: "Website Redesign",
        createdAt: "15.01.2024",
        members: 5,
        isOwner: true,
        status: "active",
        tasks: {
            total: 12,
            completed: 8,
        },
    },
    {
        id: "2",
        name: "Mobile App Development",
        createdAt: "03.02.2024",
        members: 8,
        isOwner: false,
        status: "paused",
        tasks: {
            total: 24,
            completed: 20,
        },
    },
    {
        id: "3",
        name: "Marketing Campaign",
        createdAt: "22.03.2024",
        members: 3,
        isOwner: true,
        status: "completed",
        tasks: {
            total: 15,
            completed: 15,
        },
    },
    {
        id: "4",
        name: "Data Analytics Dashboard",
        createdAt: "01.04.2024",
        members: 6,
        isOwner: true,
        status: "active",
        tasks: {
            total: 18,
            completed: 7,
        },
    },
    {
        id: "5",
        name: "User Authentication System",
        createdAt: "05.04.2024",
        members: 4,
        isOwner: false,
        status: "paused",
        tasks: {
            total: 16,
            completed: 4,
        },
    },
    {
        id: "6",
        name: "Cloud Migration",
        createdAt: "10.04.2024",
        members: 7,
        isOwner: true,
        status: "active",
        tasks: {
            total: 22,
            completed: 15,
        },
    },
    {
        id: "7",
        name: "Mobile App Testing",
        createdAt: "15.04.2024",
        members: 5,
        isOwner: false,
        status: "completed",
        tasks: {
            total: 14,
            completed: 14,
        },
    },
    {
        id: "8",
        name: "API Integration",
        createdAt: "20.04.2024",
        members: 4,
        isOwner: true,
        status: "active",
        tasks: {
            total: 20,
            completed: 12,
        },
    },
    {
        id: "9",
        name: "Performance Optimization",
        createdAt: "25.04.2024",
        members: 3,
        isOwner: true,
        status: "paused",
        tasks: {
            total: 10,
            completed: 3,
        },
    },
] 